// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, http, util;

  http = require("http");

  express = require("express");

  util = require('util');

  app = express();

  app.use(express["static"]("./public"));

  app.use(app.router);

  app.set('view engine', 'jade');

  app.set('views', './views');

  app.use(express.responseTime());

  app.use(express.json());

  app.use(express.urlencoded());

  app.get("/", function(req, res) {
    return res.render('index');
  });

  app.get("/upload", function(req, res) {
    return res.send("<h1>Upload!</h1>");
  });

  app.post("/upload", function(req, res) {
    var form, multiparty;
    multiparty = require('multiparty');
    form = new multiparty.Form();
    return form.parse(req, function(err, fields, files) {
      if (err) {
        res.writeHead(500, {
          "content-type": "text/plain"
        });
        res.end("ERROR: uploading\n\n");
      }
      console.log("upload", fields, files);
      res.json(util.inspect({
        fields: fields,
        files: files
      }));
    });
  });

  http.createServer(app).listen(process.env.PORT, function() {
    return console.log('App Started');
  });

}).call(this);
